;$(function() {

var form1 = document.getElementById("form1");
var form2 = document.getElementById("form2");
var form3 = document.getElementById("form3");
var form4 = document.getElementById("form4");
var form5 = document.getElementById("form5");
var form6 = document.getElementById("form6");
var form7 = document.getElementById("form7");
var form8 = document.getElementById("form8");
var form9 = document.getElementById("form9");
var form10 = document.getElementById("form10");
var form11 = document.getElementById("form11");
var form12 = document.getElementById("form12");
var form13 = document.getElementById("form13");
var form14 = document.getElementById("form14");
var form15 = document.getElementById("form15");
var form16 = document.getElementById("form16");
var form17 = document.getElementById("form17");
var form18 = document.getElementById("form18");
var form19 = document.getElementById("form19");
var form20 = document.getElementById("form20");
var form21 = document.getElementById("form21");
var form22 = document.getElementById("form22");
var form23 = document.getElementById("form23");
var form24 = document.getElementById("form24");
var form25 = document.getElementById("form25");
var form26 = document.getElementById("form26");

katex.render("{3\\frac{10}{71} < \\pi < 3\\frac{1}{7}}", form1);
katex.render("{\\frac{\\pi}{4} = 1 - \\frac{1}{3} + \\frac{1}{5} - \\frac{1}{7} + \\ldots,}", form2);
katex.render("{\\frac{2}{\\pi} = \\frac{\\sqrt{2}}{2}\\cdot \\frac{\\sqrt{2+\\sqrt{2}}}{2}\\cdot \\frac{\\sqrt{2+\\sqrt{2+\\sqrt{2}}}}{2} \\ldots,}", form3);
katex.render("{\\frac{\\pi}{2} = \\frac{2}{1}\\cdot \\frac{2}{3}\\cdot \\frac{4}{3}\\cdot \\frac{4}{5}\\cdot \\frac{6}{5}\\cdot \\frac{6}{7}\\ldots .}", form4);
katex.render("{2\\sqrt{2} < \\pi < 4}", form5);
katex.render("{\\displaystyle e:=\\lim_{n\\rightarrow\\infty}\\left(1+\\frac{1}{n}\\right)^{n},}", form6);
katex.render("{\\displaystyle e=1+\\frac{1}{1!}+\\frac{1}{2!}+\\frac{1}{3!}+\\frac{1}{4!}+\\ldots,}", form7);
katex.render("{\\displaystyle e=\\lim_{n\\rightarrow\\infty}\\frac{n}{{}^{n}\\sqrt{n!}}.}", form8);
katex.render("{\\displaystyle \\zeta(3) = 1+\\frac{1}{2^{3}}+\\frac{1}{3^{3}}+\\frac{1}{4^{3}}+\\ldots \\approx 1.202\\ldots .}", form9);
katex.render("{\\zeta(k)=1+\\frac{1}{2^{k}}+\\frac{1}{3^{k}}+\\frac{1}{4^{k}}+\\ldots}", form10);
katex.render("{\\displaystyle \\varphi=\\frac{a}{b} = \\frac{a+b}{a} = 1 + \\frac{1}{\\varphi}.}", form11);
katex.render("{\\displaystyle \\varphi=\\frac{1+\\sqrt{5}}{2}\\approx1.618\\ldots.}", form12);
katex.render("{\\displaystyle \\varphi=\\lim_{n\\rightarrow\\infty}\\frac{F_{n+1}}{F_{n}}.}", form13);
katex.render("{F_{n}=\\frac{\\varphi^{n}-(1-\\varphi)^{n}}{\\sqrt{5}}.}", form14);
katex.render("{\\displaystyle \\rho={}^{3}\\sqrt{\\frac{1}{2}+\\frac{1}{6}\\sqrt{\\frac{23}{3}}}+{}^{3}\\sqrt{\\frac{1}{2}-\\frac{1}{6}\\sqrt{\\frac{23}{3}}}\\approx1.3247\\ldots.}", form15);
katex.render("{\\displaystyle \\lim_{n\\rightarrow\\infty}\\frac{A_{n+1}}{A_{n}}=\\rho=\\lim_{n\\rightarrow\\infty}\\frac{P_{n+1}}{P_{n}}.}", form16);
katex.render("{\\sqrt{2}}", form17);
katex.render("{\\sqrt{2}}", form18);
katex.render("{\\sqrt{2}}", form19);
katex.render("{\\sqrt{2}}", form20);
katex.render("{\\sqrt{2}}", form21);
katex.render("{\\sqrt{2} = 1 + \\frac{1}{2+\\frac{1}{2+\\frac{1}{2+\\ldots}}},}", form22);
katex.render("{\\sqrt{2} = \\left ( 1+\\frac{1}{1} \\right )\\left ( 1-\\frac{1}{3} \\right )\\left ( 1+\\frac{1}{5} \\right )\\ldots,}", form23);
katex.render("{\\sqrt{2}^{\\sqrt{2}^{\\sqrt{2}^{\\sqrt{2}^{\\ldots}}}} = 2.}", form24);
katex.render("{\\sqrt{2}}", form25);
katex.render("{\\sqrt{m}}", form26);

});	